import type { FieldMapping } from '../../fill-engine/types.js';

/**
 * One mapping table for all job boards.
 * Matching uses label text, name, id, aria-label, placeholder — not provider-specific DOM.
 */
export const UNIVERSAL_FIELD_MAPPINGS: FieldMapping[] = [
  {
    labelSynonyms: ['first name', 'given name', 'legal first name'],
    namePattern: /first[_\[\].-]?name|given/i,
    idPattern: /first[_-]?name|given/i,
    automationIdPattern: /first.?name/i,
    jsonPath: 'profile.first_name',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['last name', 'family name', 'surname', 'legal last name'],
    namePattern: /last[_\[\].-]?name|family|surname/i,
    idPattern: /last[_-]?name|family|surname/i,
    automationIdPattern: /last.?name/i,
    jsonPath: 'profile.last_name',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['email', 'email address', 'contact email'],
    namePattern: /email/i,
    idPattern: /^email$/i,
    automationIdPattern: 'email',
    jsonPath: 'profile.email',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['phone number', 'phone'],
    namePattern: /(?:^|\[)(?:phone[_-]?number|phone)(?:\]|$)/i,
    idPattern: /^phone(?:[_-]?number)?$/i,
    jsonPath: 'profile.phone.number',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['country phone code', 'phone country code', 'country code'],
    namePattern: /country.*phone.*code|phone.*country.*code|phone_country|country_phone/i,
    idPattern: /country.*phone.*code|phone.*country.*code/i,
    jsonPath: 'profile.address.country',
    fieldType: 'dropdown',
  },
  {
    labelSynonyms: ['country'],
    namePattern: /(?:^|\[)country(?:\]|$)|^country$/i,
    idPattern: /^country$/i,
    automationIdPattern: /^country$/i,
    jsonPath: 'profile.address.country',
    fieldType: 'dropdown',
  },
  {
    labelSynonyms: ['city', 'town'],
    namePattern: /city|town/i,
    idPattern: /city|town/i,
    automationIdPattern: /city/i,
    jsonPath: 'profile.address.city',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['state', 'province', 'region'],
    namePattern: /state|province|region/i,
    idPattern: /state|province|region/i,
    automationIdPattern: /state/i,
    jsonPath: 'profile.address.state',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['postal code', 'zip', 'zip code', 'pin code'],
    namePattern: /postal|zip|pin/i,
    idPattern: /postal|zip|pin/i,
    automationIdPattern: /postal|zip/i,
    jsonPath: 'profile.address.postal_code',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['address line 1', 'street address', 'address', 'home address'],
    namePattern: /address|street|line1/i,
    idPattern: /address|street|line1/i,
    automationIdPattern: /address.*line1|street/i,
    jsonPath: 'profile.address.line1',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['address line 2', 'apt', 'suite', 'unit'],
    namePattern: /line2|apt|suite|unit/i,
    idPattern: /line2|apt|suite|unit/i,
    jsonPath: 'profile.address.line2',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['linkedin profile', 'linkedin', 'linkedin url'],
    namePattern: /linkedin/i,
    idPattern: /linkedin/i,
    automationIdPattern: /linkedin/i,
    jsonPath: 'profile.social.linkedin',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['website', 'personal website', 'portfolio'],
    namePattern: /website|portfolio|url/i,
    idPattern: /website|portfolio/i,
    automationIdPattern: /website|portfolio/i,
    jsonPath: 'profile.social.website',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['github'],
    namePattern: /github/i,
    jsonPath: 'profile.social.github',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['summary', 'about you', 'professional summary'],
    namePattern: /summary|about/i,
    idPattern: /summary|about/i,
    automationIdPattern: /summary|about/i,
    jsonPath: 'profile.summary',
    fieldType: 'textarea',
  },
  {
    labelSynonyms: ['cover letter'],
    namePattern: /cover[_\[\].-]?letter/i,
    jsonPath: 'cover_letter',
    fieldType: 'textarea',
  },
  {
    labelSynonyms: ['skills', 'skill'],
    namePattern: /skill/i,
    automationIdPattern: /skill/i,
    jsonPath: 'profile.skills',
    fieldType: 'multiselect',
  },
  {
    labelSynonyms: ['years of experience'],
    namePattern: /years.*experience|experience.*years/i,
    jsonPath: 'preferences.years_of_experience',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['desired salary', 'salary', 'compensation'],
    namePattern: /salary|compensation/i,
    jsonPath: 'preferences.desired_salary',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['current company', 'company', 'employer'],
    namePattern: /company|employer/i,
    jsonPath: 'work_experience[0].company',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['current title', 'job title'],
    namePattern: /job[_\[\].-]?title|current_title/i,
    jsonPath: 'work_experience[0].title',
    fieldType: 'text',
  },
  {
    labelSynonyms: ['resume', 'resume/cv', 'cv', 'upload resume'],
    namePattern: /resume|cv/i,
    idPattern: /resume|cv/i,
    automationIdPattern: /resume|cv/i,
    jsonPath: 'resume_filename',
    fieldType: 'file',
  },
  {
    labelSynonyms: ['i agree', 'terms', 'privacy policy', 'confidential information'],
    namePattern: /agree|consent|privacy|terms/i,
    jsonPath: 'legal.terms_accepted',
    fieldType: 'checkbox',
  },
];
